-- Auto-generated by matugen - DON'T EDIT
return {
	wallpaper = "/home/sudobytemebaby/Pictures/Wallpapers/sandip-kalal-91nZwaM5fz8-unsplash.jpg",

	-- accents
	accent = "rgba(c3c0ffff)",
	accent_fixed = "rgba(e2dfffff)",
	secondary = "rgba(c7c4ddff)",
	secondary_fixed = "rgba(e3e0f9ff)",
	tertiary = "rgba(eab9d2ff)",
	tertiary_fixed = "rgba(ffd8eaff)",

	-- background layers
	bg0 = "rgba(131316ff)",
	bg1 = "rgba(201f23ff)",
	bg2 = "rgba(1c1b1fff)",
	bg_bright = "rgba(3a393cff)",
	bg_dim = "rgba(131316ff)",

	-- error
	error = "rgba(ffb4abff)",
	on_error = "rgba(690005ff)",

	-- text
	fg = "rgba(c8c5d0ff)",
	fg_strong = "rgba(e5e1e6ff)",
	fg_muted = "rgba(c8c5d0ff)",

	-- borders
	border = "rgba(47464fff)",
	border_strong = "rgba(928f9aff)",
	border_dim = "rgba(313034ff)",

	-- overlays
	overlay = "rgba(000000ff)",
	scrim = "rgba(000000ff)",
}
