-- Auto-generated by matugen - DON'T EDIT
return {
	wallpaper = "/home/sudobytemebaby/Pictures/Wallpapers/kanagawa_pool.jpg",

	-- accents
	accent = "rgba(b5c4ffff)",
	accent_fixed = "rgba(dce1ffff)",
	secondary = "rgba(c2c5ddff)",
	secondary_fixed = "rgba(dee1f9ff)",
	tertiary = "rgba(e3badaff)",
	tertiary_fixed = "rgba(ffd7f6ff)",

	-- background layers
	bg0 = "rgba(131316ff)",
	bg1 = "rgba(1f1f23ff)",
	bg2 = "rgba(1b1b1fff)",
	bg_bright = "rgba(39393cff)",
	bg_dim = "rgba(131316ff)",

	-- error
	error = "rgba(ffb4abff)",
	on_error = "rgba(690005ff)",

	-- text
	fg = "rgba(c6c6d0ff)",
	fg_strong = "rgba(e4e2e6ff)",
	fg_muted = "rgba(c6c6d0ff)",

	-- borders
	border = "rgba(45464fff)",
	border_strong = "rgba(8f909aff)",
	border_dim = "rgba(303034ff)",

	-- overlays
	overlay = "rgba(000000ff)",
	scrim = "rgba(000000ff)",
}
