# ----- Generated theme by matugen for tmux -----
set -g @accent  "#bdcab9"
set -g @secondary "#c1c9be"
set -g @tertiary  "#b8ccb5"
set -g @bg0       "#1f201e"
set -g @bg1       "#292a28"
set -g @error     "#ffb4ab"
set -g @on_error  "#690005"
set -g @fg        "#e4e2df"
set -g @fg_muted  "#464745"
set -g @border    "#464745"
