# ----- Generated theme by matugen for tmux -----
set -g @accent  "#b1c5ff"
set -g @secondary "#bfc6df"
set -g @tertiary  "#eeb4e6"
set -g @bg0       "#1f1f23"
set -g @bg1       "#292a2d"
set -g @error     "#ffb4ab"
set -g @on_error  "#690005"
set -g @fg        "#e3e2e6"
set -g @fg_muted  "#44464f"
set -g @border    "#44464f"
