# ----- Generated theme by matugen for tmux -----
set -g @accent  "#b5c4ff"
set -g @secondary "#c2c5dd"
set -g @tertiary  "#e3bada"
set -g @bg0       "#1f1f23"
set -g @bg1       "#292a2d"
set -g @error     "#ffb4ab"
set -g @on_error  "#690005"
set -g @fg        "#e4e2e6"
set -g @fg_muted  "#45464f"
set -g @border    "#45464f"
