[colors-dark]
foreground=e2e2e9
background=1e1f25
selection-foreground=293041
selection-background=bfc6dc
urls=adc6ff

## black
regular0=262626
bright0=4c4c4c

## red
regular1=ac8a8c
bright1=c49ea0

## green
regular2=8aac8b
bright2=9ec49f

## yellow
regular3=aca98a
bright3=c4c19e

## blue
regular4=adc6ff
bright4=a39ec4

## magenta
regular5=ac8aac
bright5=c49ec4

## cyan
regular6=8aacab
bright6=9ec3c4

## white
regular7=f0f0f0
bright7=e7e7e7
