[main]
include=~/.config/foot/colors.ini

# Default terminal shell
shell=/usr/bin/fish

# Font configuration
font=JetBrainsMono Nerd Font:size=13

font-bold=JetBrainsMono Nerd Font:weight=bold:size=13
font-italic=JetBrainsMono Nerd Font:slant=italic:size=13
font-bold-italic=JetBrainsMono Nerd Font:weight=bold:slant=italic:size=13

# padding = <horizontal>x<vertical>
pad=10x10

# Including themes
#include=~/.config/foot/colors.ini

[scrollback]
lines=2000
multiplier=1.0

[cursor]
style=block
