$background = 0d0e12
$onBackground = e5e4f0
$surface = 0d0e12
$surfaceDim = 0d0e12
$surfaceBright = 2a2c34
$surfaceContainerLowest = 000000
$surfaceContainerLow = 121318
$surfaceContainer = 181920
$surfaceContainerHigh = 1e1f26
$surfaceContainerHighest = 24252e
$onSurface = e5e4f0
$surfaceVariant = 24252e
$onSurfaceVariant = aaaab5
$outline = 74757f
$outlineVariant = 464750
$inverseSurface = fbf8fe
$inverseOnSurface = 55545a
$shadow = 000000
$scrim = 000000
$surfaceTint = bdc5ee
$primary = bdc5ee
$primaryDim = afb7e0
$onPrimary = 363e61
$primaryContainer = 495174
$onPrimaryContainer = dee2ff
$inversePrimary = 555d82
$primaryFixed = cbd2fd
$primaryFixedDim = bdc5ee
$onPrimaryFixed = 2c3456
$onPrimaryFixedVariant = 495174
$secondary = c2c5dd
$secondaryDim = b4b7cf
$onSecondary = 3b3f52
$secondaryContainer = 373a4d
$onSecondaryContainer = bbbed5
$secondaryFixed = dee1f9
$secondaryFixedDim = d0d3eb
$onSecondaryFixed = 3b3e51
$onSecondaryFixedVariant = 575a6f
$tertiary = f7e1ff
$tertiaryDim = efcffe
$onTertiary = 644c73
$tertiaryContainer = efcffe
$onTertiaryContainer = 5b436a
$tertiaryFixed = efcffe
$tertiaryFixedDim = e0c1ef
$onTertiaryFixed = 483156
$onTertiaryFixedVariant = 654d74
$error = f97386
$errorDim = c44b5f
$onError = 490013
$errorContainer = 871c34
$onErrorContainer = ff97a3
$primaryPaletteKeyColor = 6d759b
$secondaryPaletteKeyColor = 72768b
$tertiaryPaletteKeyColor = 886d97
$neutralPaletteKeyColor = 77767b
$neutralVariantPaletteKeyColor = 767680
$errorPaletteKeyColor = c74d61
$primary_paletteKeyColor = 6d759b
$secondary_paletteKeyColor = 72768b
$tertiary_paletteKeyColor = 886d97
$neutral_paletteKeyColor = 77767b
$neutral_variant_paletteKeyColor = 767680
$term0 = 353434
$term1 = 9c7aff
$term2 = 44def5
$term3 = ffdcf2
$term4 = 93abd6
$term5 = aaa1ed
$term6 = 9dceff
$term7 = e8d3de
$term8 = ac9fa9
$term9 = b399ff
$term10 = 89ecff
$term11 = fff0f6
$term12 = b1c2db
$term13 = c1b7f7
$term14 = bae0ff
$term15 = ffffff
$rosewater = f6eff9
$flamingo = e6def4
$pink = ddd9ff
$mauve = b6bbff
$red = b6a9ff
$maroon = c2b7ef
$peach = e0c2f9
$yellow = ffecf3
$green = c8e3ff
$teal = cfe1ff
$sky = cadbff
$sapphire = afc7ff
$blue = a6baff
$lavender = c0caff
$klink = 6685d1
$klinkSelection = 6685d1
$kvisited = 7276dd
$kvisitedSelection = 7376dd
$knegative = 8e70ff
$knegativeSelection = 8f70ff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 54afff
$kpositiveSelection = 55afff
$text = e5e4f0
$subtext1 = aaaab5
$subtext0 = 74757f
$overlay2 = 65666f
$overlay1 = 56575f
$overlay0 = 484950
$surface2 = 3a3b41
$surface1 = 2c2d32
$surface0 = 1c1d22
$base = 0d0e12
$mantle = 0d0e12
$crust = 0c0d11
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
