pragma Singleton
import QtQuick

QtObject {
    // ============================================================================
    // MATUGEN SEMANTIC TOKENS (Material Design 3)
    // ============================================================================
    // These values are generated by matugen from your wallpaper
    
    // --- Primary Colors (Main brand color) ---
    readonly property color primary: "{{colors.primary.default.hex}}"
    readonly property color on_primary: "{{colors.on_primary.default.hex}}"
    readonly property color primary_container: "{{colors.primary_container.default.hex}}"
    readonly property color on_primary_container: "{{colors.on_primary_container.default.hex}}"
    readonly property color primary_fixed: "{{colors.primary_fixed.default.hex}}"
    readonly property color primary_fixed_dim: "{{colors.primary_fixed_dim.default.hex}}"
    readonly property color on_primary_fixed: "{{colors.on_primary_fixed.default.hex}}"
    readonly property color on_primary_fixed_variant: "{{colors.on_primary_fixed_variant.default.hex}}"
    
    // --- Secondary Colors (Supporting color) ---
    readonly property color secondary: "{{colors.secondary.default.hex}}"
    readonly property color on_secondary: "{{colors.on_secondary.default.hex}}"
    readonly property color secondary_container: "{{colors.secondary_container.default.hex}}"
    readonly property color on_secondary_container: "{{colors.on_secondary_container.default.hex}}"
    readonly property color secondary_fixed: "{{colors.secondary_fixed.default.hex}}"
    readonly property color secondary_fixed_dim: "{{colors.secondary_fixed_dim.default.hex}}"
    readonly property color on_secondary_fixed: "{{colors.on_secondary_fixed.default.hex}}"
    readonly property color on_secondary_fixed_variant: "{{colors.on_secondary_fixed_variant.default.hex}}"
    
    // --- Tertiary Colors (Third accent) ---
    readonly property color tertiary: "{{colors.tertiary.default.hex}}"
    readonly property color on_tertiary: "{{colors.on_tertiary.default.hex}}"
    readonly property color tertiary_container: "{{colors.tertiary_container.default.hex}}"
    readonly property color on_tertiary_container: "{{colors.on_tertiary_container.default.hex}}"
    readonly property color tertiary_fixed: "{{colors.tertiary_fixed.default.hex}}"
    readonly property color tertiary_fixed_dim: "{{colors.tertiary_fixed_dim.default.hex}}"
    readonly property color on_tertiary_fixed: "{{colors.on_tertiary_fixed.default.hex}}"
    readonly property color on_tertiary_fixed_variant: "{{colors.on_tertiary_fixed_variant.default.hex}}"
    
    // --- Error Colors ---
    readonly property color error: "{{colors.error.default.hex}}"
    readonly property color on_error: "{{colors.on_error.default.hex}}"
    readonly property color error_container: "{{colors.error_container.default.hex}}"
    readonly property color on_error_container: "{{colors.on_error_container.default.hex}}"
    
    // --- Background Colors ---
    readonly property color background: "{{colors.background.default.hex}}"
    readonly property color on_background: "{{colors.on_background.default.hex}}"
    
    // --- Surface Colors (5-level elevation system) ---
    readonly property color surface: "{{colors.surface.default.hex}}"
    readonly property color on_surface: "{{colors.on_surface.default.hex}}"
    readonly property color surface_variant: "{{colors.surface_variant.default.hex}}"
    readonly property color on_surface_variant: "{{colors.on_surface_variant.default.hex}}"
    
    readonly property color surface_dim: "{{colors.surface_dim.default.hex}}"
    readonly property color surface_bright: "{{colors.surface_bright.default.hex}}"
    readonly property color surface_container_lowest: "{{colors.surface_container_lowest.default.hex}}"
    readonly property color surface_container_low: "{{colors.surface_container_low.default.hex}}"
    readonly property color surface_container: "{{colors.surface_container.default.hex}}"
    readonly property color surface_container_high: "{{colors.surface_container_high.default.hex}}"
    readonly property color surface_container_highest: "{{colors.surface_container_highest.default.hex}}"
    
    // --- Outline Colors (Borders) ---
    readonly property color outline: "{{colors.outline.default.hex}}"
    readonly property color outline_variant: "{{colors.outline_variant.default.hex}}"
    
    // --- Inverse Colors (for dark/light theme switching) ---
    readonly property color inverse_surface: "{{colors.inverse_surface.default.hex}}"
    readonly property color inverse_on_surface: "{{colors.inverse_on_surface.default.hex}}"
    readonly property color inverse_primary: "{{colors.inverse_primary.default.hex}}"
    
    // --- Scrim & Shadow ---
    readonly property color scrim: "{{colors.scrim.default.hex}}"
    readonly property color shadow: "{{colors.shadow.default.hex}}"
    
    // ============================================================================
    // TRANSPARENT VARIANTS - FOR BLUR EFFECTS
    // ============================================================================
    // Use these with Hyprland blur for beautiful frosted glass effects!
    // Light = 50-65% opacity (subtle blur)
    // Medium = 70-80% opacity (balanced blur)
    // Heavy = 85-92% opacity (strong blur, more opaque)
    
    // --- Primary Transparencies ---
    readonly property color primary_transparent: Qt.rgba(primary.r, primary.g, primary.b, 0.12)
    readonly property color primary_transparent_medium: Qt.rgba(primary.r, primary.g, primary.b, 0.25)
    readonly property color primary_transparent_heavy: Qt.rgba(primary.r, primary.g, primary.b, 0.40)
    
    // --- Surface Transparencies (for backgrounds) ---
    readonly property color surface_transparent: Qt.rgba(surface.r, surface.g, surface.b, 0.12)
    readonly property color surface_transparent_light: Qt.rgba(surface.r, surface.g, surface.b, 0.50)
    readonly property color surface_transparent_medium: Qt.rgba(surface.r, surface.g, surface.b, 0.70)
    readonly property color surface_transparent_heavy: Qt.rgba(surface.r, surface.g, surface.b, 0.85)
    
    // --- Surface Container Transparencies (for main panels/popups) ---
    // RECOMMENDED: Use these for Control Center, Calendar, Launcher, etc.
    readonly property color surface_container_transparent: Qt.rgba(surface_container.r, surface_container.g, surface_container.b, 0.12)
    readonly property color surface_container_transparent_light: Qt.rgba(surface_container.r, surface_container.g, surface_container.b, 0.60)
    readonly property color surface_container_transparent_medium: Qt.rgba(surface_container.r, surface_container.g, surface_container.b, 0.75)
    readonly property color surface_container_transparent_heavy: Qt.rgba(surface_container.r, surface_container.g, surface_container.b, 0.90)
    
    // --- Surface Container Low Transparencies (for cards/items) ---
    readonly property color surface_container_low_transparent_light: Qt.rgba(surface_container_low.r, surface_container_low.g, surface_container_low.b, 0.65)
    readonly property color surface_container_low_transparent_medium: Qt.rgba(surface_container_low.r, surface_container_low.g, surface_container_low.b, 0.80)
    readonly property color surface_container_low_transparent_heavy: Qt.rgba(surface_container_low.r, surface_container_low.g, surface_container_low.b, 0.92)

    // --- Surface Container High Transparencies (for cards/items) ---
    readonly property color surface_container_high_transparent_light: Qt.rgba(surface_container_high.r, surface_container_high.g, surface_container_high.b, 0.65)
    readonly property color surface_container_high_transparent_medium: Qt.rgba(surface_container_high.r, surface_container_high.g, surface_container_high.b, 0.80)
    readonly property color surface_container_high_transparent_heavy: Qt.rgba(surface_container_high.r, surface_container_high.g, surface_container_high.b, 0.92)
    
    // --- Scrim Transparencies (for modal overlays) ---
    readonly property color scrim_transparent: Qt.rgba(scrim.r, scrim.g, scrim.b, 0.32)
    readonly property color scrim_transparent_light: Qt.rgba(scrim.r, scrim.g, scrim.b, 0.15)
    readonly property color scrim_transparent_medium: Qt.rgba(scrim.r, scrim.g, scrim.b, 0.45)
    readonly property color scrim_transparent_heavy: Qt.rgba(scrim.r, scrim.g, scrim.b, 0.65)
    
    // ============================================================================
    // SPACING SYSTEM
    // ============================================================================
    
    readonly property QtObject spacing: QtObject {
        readonly property int xs: 4
        readonly property int sm: 8
        readonly property int md: 12
        readonly property int lg: 18
        readonly property int xl: 26 
        readonly property int xxl: 48
    }
    
    // ============================================================================
    // PADDING SYSTEM
    // ============================================================================
    
    readonly property QtObject padding: QtObject {
        readonly property int xs: 4
        readonly property int sm: 8
        readonly property int md: 12
        readonly property int lg: 18
        readonly property int xl: 20
    }
    
    // ============================================================================
    // TYPOGRAPHY SYSTEM
    // ============================================================================
    
    readonly property QtObject typography: QtObject {
        readonly property string fontFamily: "Ubuntu Nerd Font Propo"
        
        readonly property int xs: 10
        readonly property int sm: 12
        readonly property int md: 14
        readonly property int lg: 16
        readonly property int xl: 18
        readonly property int xxl: 24
        readonly property int xxxl: 32
        
        readonly property int weightNormal: 400
        readonly property int weightMedium: 500
        readonly property int weightBold: 700
    }
    
    // ============================================================================
    // SHAPE SYSTEM (Border Radius)
    // ============================================================================
    
    readonly property QtObject radius: QtObject {
        readonly property int none: 0
        readonly property int sm: 6
        readonly property int md: 12
        readonly property int lg: 20
        readonly property int xl: 32 
        readonly property int xxl: 40
        readonly property int full: 9999
    }
    
    // ============================================================================
    // COMPONENT TOKENS
    // ============================================================================
    
    readonly property QtObject component: QtObject {
        readonly property int barHeight: 26
        readonly property int workspaceIndicatorSize: 10
        readonly property int buttonHeight: 36
        readonly property int inputHeight: 40
    }
    
    // ============================================================================
    // LEGACY ALIASES (for backward compatibility)
    // ============================================================================
    // These allow your existing code to work without changes
    
    readonly property color accent: primary
    readonly property color accentTransparent: primary_transparent
    readonly property color accentFixed: primary_fixed
    readonly property color bg0: surface
    readonly property color bg0transparent: surface_transparent
    readonly property color bg1: surface_container
    readonly property color bg1transparent: surface_container_transparent
    readonly property color bg1transparentLauncher: surface_container_transparent_medium
    readonly property color bg2: surface_container_low
    readonly property color bg2transparent: surface_container_low_transparent_medium
    readonly property color bgBright: surface_bright
    readonly property color bgDim: surface_dim
    readonly property color fg: on_surface
    readonly property color fgStrong: on_surface
    readonly property color fgMuted: on_surface_variant
    readonly property color border: outline
    readonly property color borderStrong: primary
    readonly property color borderDim: outline_variant
    readonly property color backgroundTransparent: surface_transparent
    
    // Spacing aliases
    readonly property int spacingXSmall: spacing.xs
    readonly property int spacingSmall: spacing.sm
    readonly property int spacingMedium: spacing.md
    readonly property int spacingLarge: spacing.lg
    readonly property int spacingXLarge: spacing.xl
    readonly property int spacingXS: spacing.xs
    readonly property int spacingS: spacing.sm
    readonly property int spacingM: spacing.md
    readonly property int spacingL: spacing.lg
    readonly property int spacingXL: spacing.xl
    
    // Margin aliases
    readonly property int marginXSmall: padding.xs
    readonly property int marginSmall: padding.sm
    readonly property int marginMedium: padding.md
    readonly property int marginLarge: padding.lg
    readonly property int marginXLarge: padding.xl
    readonly property int marginXS: padding.xs
    readonly property int marginS: padding.sm
    readonly property int marginM: padding.md
    readonly property int marginL: padding.lg
    readonly property int marginXL: padding.xl
    
    // Font aliases
    readonly property string fontFamily: typography.fontFamily
    readonly property int fontSizeXSmall: typography.xs
    readonly property int fontSizeSmall: typography.sm
    readonly property int fontSizeMedium: typography.md
    readonly property int fontSizeLarge: typography.lg
    readonly property int fontSizeXLarge: typography.xl
    readonly property int fontSizeXS: typography.xs
    readonly property int fontSizeS: typography.sm
    readonly property int fontSizeM: typography.md
    readonly property int fontSizeL: typography.lg
    readonly property int fontSizeXL: typography.xl
    
    // Radius aliases
    readonly property int radiusSmall: radius.sm
    readonly property int radiusMedium: radius.md
    readonly property int radiusLarge: radius.lg
    readonly property int radiusXLarge: radius.xl
    
    // Component aliases
    readonly property int barHeight: component.barHeight
    readonly property int workspaceIndicatorSize: component.workspaceIndicatorSize
}
