# ---------------------------------------------------------------------------
# Misc
# ---------------------------------------------------------------------------

# Отключаем splash-текст "Hyprland" поверх обоев
splash = false

# IPC-сокет оставляем включённым — нужен для hyprctl hyprpaper wallpaper
# и любых скриптов смены обоев на лету
ipc = true

# ---------------------------------------------------------------------------
# Wallpapers
# ---------------------------------------------------------------------------

# Конкретный монитор — узнать своё имя: hyprctl monitors | grep Monitor
wallpaper {
    monitor  = eDP-1
    path     = /home/sudobytemebaby/Pictures/Wallpapers/kanagawa_pool.jpg
    fit_mode = cover
}

# Fallback — применяется к любому монитору, которому не назначена
# явная запись выше. Удобно если имя монитора вдруг поменяется
# или подключить внешний дисплей
wallpaper {
    monitor  =
    path     = /home/sudobytemebaby/Pictures/Wallpapers/kanagawa_pool.jpg
    fit_mode = cover
}
