general {
  # Lock using hyprlock; pidof guard avoids spawning multiple instances
	lock_cmd = pidof hyprlock || noctalia msg session lock
  # Locks before suspend
	before_sleep_cmd = noctalia msg sesssion lock
  # To avoid having to press a key twice to turn on the display
	after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# Decrease screen brightness after X amount of time
listener {
  timeout    = 150 # 2.5 minutes
  on-timeout = brightnessctl -s set 25%
  on-resume  = brightnessctl -r
}

# Turns off kb backlight after X amount of time
listener {
  timeout    = 150 # 2.5 minutes
  on-timeout = brightnessctl -sd platform::kbd_backlight set 0
  on-resume  = brightnessctl -rd platform::kbd_backlight
}

# Locks session after X amount of time
listener {
  timeout    = 300 # 5 minutes
  on-timeout = loginctl lock-session
}

# Turns off display after X amount of time
listener {
  timeout    = 330 # 5.5 minutes
  on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
  on-resume  = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# Suspends after X amount of time
listener {
  timeout    = 1800 # 30 minutes
  on-timeout = systemctl suspend
}
