[config]

[templates.hyprland]
input_path = "~/.config/noctalia/templates/hyprland/colors.lua"
output_path = "~/.config/hypr/lua/colors.lua"

[templates.tmux]
input_path = "~/.config/noctalia/templates/tmux/colors.conf"
output_path = "~/.config/tmux/colors.conf"

[templates.foot]
input_path = "~/.config/noctalia/templates/foot/colors.ini"
output_path = "~/.config/foot/colors.ini"

[templates.yazi]
input_path = "~/.config/noctalia/templates/yazi/theme.toml"
output_path = "~/.config/yazi/theme.toml"
