# : Manager [[[

[mgr]
cwd = { fg = "#e5e1e6" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#ff72b3", bg = "#ff72b3" }
marker_cut      = { fg = "#ffd8ea", bg = "#ffd8ea" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#eab9d2", bg = "#eab9d2" }

# Count
count_copied   = { fg = "#2f1124", bg = "#ffd8ea" }
count_cut      = { fg = "#2f1124", bg = "#ffd8ea" }
count_selected = { fg = "#272377", bg = "#eab9d2" }

# Border
border_symbol = "│"
border_style  = { fg = "#c3c0ff" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#c3c0ff", bold = true, bg = "#131316" }
inactive  = { fg = "#c7c4dd", bg = "#131316" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#c3c0ff", fg = "#272377", bold = true }
normal_alt  = { bg = "#47464f", fg = "#c8c5d0" }

# Select mode
select_main = { bg = "#c7c4dd", fg = "#2f2e42", bold = true }
select_alt  = { bg = "#47464f", fg = "#c8c5d0" }

# Unset mode
unset_main = { bg = "#eab9d2", fg = "#472639", bold = true }
unset_alt  = { bg = "#47464f", fg = "#c8c5d0" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#6b63a5" }
perm_write = { fg = "#c74386" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#ff3f98" }
perm_sep   = { fg = "#5746ff" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#c3c0ff", bg = "#3a393c" }
progress_error  = { fg = "#ffb4ab", bg = "#3a393c" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3a393c" }
cand = { fg = "#c3c0ff" }
rest = { fg = "#272377" }
desc = { fg = "#e5e1e6" }
separator = " ▶ "
separator_style = { fg = "#e5e1e6" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#eab9d2" }
title_warn  = { fg = "#c3c0ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#c3c0ff" }
active = { fg = "#eab9d2", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#c3c0ff" }
value  = { fg = "#e5e1e6" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#c3c0ff", bg = "#272377" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#c3c0ff" }
title   = {}
hovered = { fg = "#ffd8ea", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e5e1e6" }
run    = { fg = "#e5e1e6" }
footer = { fg = "#2f2e42", bg = "#c7c4dd" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e5e1e6" },
    { url = "*/", fg = "#c3c0ff" },
]

# : ]]]
