decoration {
  # ---------------- BLUR SETTINGS -----------------
  blur {
    enabled = true 
    size = 20                    # Blur size (distance)
    passes = 3                   # The amount of passes to perform 
    new_optimizations = on       # Recommended to leave on, as it will massively improve performance.
    xray = false                 # If enabled, floating windows will ignore tiled windows in their blur
    ignore_opacity = true        # Make the blur layer ignore the opacity of the window
    brightness = 0.8             # Brightness modulation for blur. [0.0 - 2.0]
    contrast = 1                 # Contrast modulation for blur. [0.0 - 2.0] 
    noise = 0.10                 # How much noise to apply. [0.0 - 1.0]
    vibrancy = 0.2               # Increase saturation of blurred colors. [0.0 - 1.0]
    vibrancy_darkness = 0.4      # How strong the effect of vibrancy is on dark areas . [0.0 - 1.0]
  }

  # ----------------- SHADOW SETTINGS --------------
  shadow {
    enabled = true
    range = 16
    render_power = 4
    offset = 1 2
    scale = 3
    color = rgba(000000aa)
  }

  # ----------------- WINDOW ROUNDING ---------------
  rounding = 10 # Rounds window corners (in pixels)
}
