# Starting shell
exec-once = hypridle 
exec-once = hyprpolkitagent 
exec-once = qs -c noctalia-shell 

# Foot terminal server
exec-once = foot --server

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only

# Auto delete trash 30 days old
exec-once = trash-empty 30

# Forward bluetooth media commands to MPRIS
exec-once = mpris-proxy

# Cursors
exec-once = hyprctl setcursor $cursorTheme $cursorSize
