# Switching between workspaces
gesture = 3, horizontal, workspace
# Closing current window
gesture = 3, down, mod: SUPER, close
# Calling hyprexpo for overview 
gesture = 3, vertical, dispatcher, hyprexpo:expo, toggle
# Fullscreen current window
gesture = 3, up,   mod: SUPER, scale: 1.5, fullscreen
