# ---------- APPLICATIONS ----------
$terminal         = foot 
$browser          = zen-browser
$file_explorer    = nautilus 
$color_picker     = hyprpicker -a
$yazi             = foot --app-id=floating_term_l -e yazi
$system_monitor   = foot --app-id=floating_term_l -e btop 

# ---------- SCREENSHOTS ----------
$screenshot_base   = ~/.local/bin/screenshot-output
$screenshot_window = ~/.local/bin/screenshot-window
$screenshot_region = ~/.local/bin/screenshot-region

# ---------- SYSTEM ----------
$wifi_menu        = qs -c noctalia-shell ipc call network togglePanel
$bluetooth_menu   = qs -c noctalia-shell ipc call bluetooth togglePanel
$audio_menu       = qs -c noctalia-shell ipc call volume togglePanel
$battery_menu     = qs -c noctalia-shell ipc call battery togglePanel

$lockscreen       = qs ipc call lockscreen lock
$bar_toggle       = qs ipc call bar toggle

# ---------- LAUNCHERS ----------
$menu_picker      = qs ipc call menu toggle
$clipboard_picker = qs -c noctalia-shell ipc call launcher clipboard
$emoji_picker     = qs ipc call emoji toggle
$powermenu        = qs ipc call powermenu toggle
$wallpaper_picker = qs ipc call wallpaper toggle
$settings         = qs -c noctalia-shell ipc call settings toggle

# ----------- OSD ------------------
$brightness_up    = brightnessctl set +5%
$brightness_down  = brightnessctl set 5%-

$input_up         = wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%+
$input_down       = wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%-
$input_mute       = wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
 
$volume_up        = wpctl set-volume @DEFAULT_SINK@ 5%+
$volume_down      = wpctl set-volume @DEFAULT_SINK@ 5%-
$volume_mute      = wpctl set-mute @DEFAULT_SINK@ toggle
