# ---------- APPLICATIONS ----------
$terminal         = footclient 
$browser          = zen-browser
$file_explorer    = nautilus 
$color_picker     = hyprpicker -a
$yazi             = footclient --app-id=floating_term_l -e yazi
$system_monitor   = footclient --app-id=floating_term_l -e btop 

# ---------- SCREENSHOTS ----------
$screenshot       = ~/.local/bin/screenshot-fullscreen

# ---------- SYSTEM ----------
$wifi_menu        = qs -c noctalia-shell ipc call network togglePanel
$bluetooth_menu   = qs -c noctalia-shell ipc call bluetooth togglePanel
$audio_menu       = qs -c noctalia-shell ipc call volume togglePanel
$battery_menu     = qs -c noctalia-shell ipc call battery togglePanel
$lockscreen       = qs -c noctalia-shell ipc call lockScreen lock
$bar_toggle       = qs -c noctalia-shell ipc call bar toggle

# ---------- LAUNCHERS ----------
$menu_picker      = qs -c noctalia-shell ipc call launcher toggle 
$clipboard_picker = qs -c noctalia-shell ipc call launcher clipboard
$emoji_picker     = qs -c noctalia-shell ipc call launcher emoji
$powermenu        = qs -c noctalia-shell ipc call sessionMenu toggle
$wallpaper_picker = qs -c noctalia-shell ipc call wallpaper toggle
$settings         = qs -c noctalia-shell ipc call settings toggle

# ----------- OSD ------------------
$brightness_up    = brightnessctl set +5%
$brightness_down  = brightnessctl set 5%-

$input_up         = wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%+
$input_down       = wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%-
$input_mute       = wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
 
$volume_up        = wpctl set-volume @DEFAULT_SINK@ 5%+
$volume_down      = wpctl set-volume @DEFAULT_SINK@ 5%-
$volume_mute      = wpctl set-mute @DEFAULT_SINK@ toggle
