# ---------- APPLICATIONS ----------
$terminal         = footclient 
$browser          = zen-browser
$file_explorer    = nautilus 
$color_picker     = hyprpicker -a
$yazi             = ~/.local/bin/tui-files
$system_monitor   = ~/.local/bin/tui-btop

# ---------- SCREENSHOTS ----------
$screenshot       = qs ipc call screenshot toggle

# ---------- SYSTEM ----------
$wifi_menu        = ~/.local/bin/tui-wifi
$bluetooth_menu   = ~/.local/bin/tui-bluetooth
$audio_menu       = ~/.local/bin/tui-audio

$lockscreen       = qs ipc call lockscreen toggle
$bar_toggle       = qs ipc call bar toggle

# ---------- LAUNCHERS ----------
$spotlight        = qs ipc call menu toggle
$clipboard_picker = qs ipc call clipboard toggle
$emoji_picker     = qs ipc call emoji toggle
$powermenu        = qs ipc call powermenu toggle
$wallpaper_picker = qs ipc call wallpaper toggle

# ----------- OSD ------------------
$brightness_up    = brightnessctl set +5%
$brightness_down  = brightnessctl set 5%-

$input_up         = wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%+
$input_down       = wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%-
$input_mute       = wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
 
$volume_up        = wpctl set-volume @DEFAULT_SINK@ 5%+
$volume_down      = wpctl set-volume @DEFAULT_SINK@ 5%-
$volume_mute      = wpctl set-mute @DEFAULT_SINK@ toggle
