-- Auto-generated by matugen - DON'T EDIT
return {
	wallpaper = "{{image}}",

	-- accents
	accent = "rgba({{colors.primary.default.hex_stripped}}ff)",
	accent_fixed = "rgba({{colors.primary_fixed.default.hex_stripped}}ff)",
	secondary = "rgba({{colors.secondary.default.hex_stripped}}ff)",
	secondary_fixed = "rgba({{colors.secondary_fixed.default.hex_stripped}}ff)",
	tertiary = "rgba({{colors.tertiary.default.hex_stripped}}ff)",
	tertiary_fixed = "rgba({{colors.tertiary_fixed.default.hex_stripped}}ff)",

	-- background layers
	bg0 = "rgba({{colors.surface.default.hex_stripped}}ff)",
	bg1 = "rgba({{colors.surface_container.default.hex_stripped}}ff)",
	bg2 = "rgba({{colors.surface_container_low.default.hex_stripped}}ff)",
	bg_bright = "rgba({{colors.surface_bright.default.hex_stripped}}ff)",
	bg_dim = "rgba({{colors.surface_dim.default.hex_stripped}}ff)",

	-- error
	error = "rgba({{colors.error.default.hex_stripped}}ff)",
	on_error = "rgba({{colors.on_error.default.hex_stripped}}ff)",

	-- text
	fg = "rgba({{colors.on_surface_variant.default.hex_stripped}}ff)",
	fg_strong = "rgba({{colors.on_surface.default.hex_stripped}}ff)",
	fg_muted = "rgba({{colors.on_surface_variant.default.hex_stripped}}ff)",

	-- borders
	border = "rgba({{colors.outline_variant.default.hex_stripped}}ff)",
	border_strong = "rgba({{colors.outline.default.hex_stripped}}ff)",
	border_dim = "rgba({{colors.inverse_on_surface.default.hex_stripped}}ff)",

	-- overlays
	overlay = "rgba({{colors.shadow.default.hex_stripped}}ff)",
	scrim = "rgba({{colors.scrim.default.hex_stripped}}ff)",
}
